services:
  - type: web
    name: device-collector
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb-uri
          property: connectionString
      - key: IPAPI_BASE
        value: https://ipapi.co
